### ISSUE TITLE
フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shunsuke-oka** [shunsuke-oka/furima-30521#9]
#自身のフリマアプリのURL
https://furima-30521.herokuapp.com/

#Basic認証のIDとパスワード
ID:  admin
pass:  2222

#出品者用のメールアドレスとパスワード
email: test111@test.com
pass: test111

#購入者用のメールアドレスとパスワード
email: test222@test.com
pass: test222

#購入用カードの番号・期限・セキュリティコード
cord: 4242424242424242
day/month: 3/23
cvc: 123

**Comment by mutorisa** [comment]
岡さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下添付画像の通り、エラーが出てしまい、挙動確認ができていない状態です。
ご確認をお願いします。
<img width="549" alt="スクリーンショット 2020-11-06 14 05 27" src="https://user-images.githubusercontent.com/65144927/98328551-58349d80-2039-11eb-9b57-38de537608a9.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A
※新しいissueを作っていただく必要はありません

**Comment by shunsuke-oka** [comment]
> 岡さん、ご提出ありがとうございます！
> 挙動確認させて頂いたところ、以下添付画像の通り、エラーが出てしまい、挙動確認ができていない状態です。
> ご確認をお願いします。
> <img alt="スクリーンショット 2020-11-06 14 05 27" width="549" src="https://user-images.githubusercontent.com/65144927/98328551-58349d80-2039-11eb-9b57-38de537608a9.png">
> 
> 修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
> https://forms.gle/dYuR1wjeHepbEhU7A
> ※新しいissueを作っていただく必要はありません

確認お願いします。

**Comment by snkw-works** [comment]
岡さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○商品を正常に出品できるよう実装しましょう。**
現在は、商品情報を全て入力した状態で「出品する」ボタンを押しても出品が出来ない（一覧に表示されない）状態です。

**○出品画面にて、画像が選択されていない場合にエラーメッセージが表示されるよう実装しましょう。**
現在は、画像を選択していなくてもエラーメッセージが出ない状態です。

**○一覧から詳細ページに遷移できるよう実装しましょう。**
現在は、一覧にて商品をクリックしても詳細に遷移しない状態です。

※上記の理由から、商品出品・購入・編集・削除の挙動確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shunsuke-oka** [comment]
> 岡さん、ご提出ありがとうございます！
> 挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
> 
> [修正箇所]
> **○商品を正常に出品できるよう実装しましょう。**
> 現在は、商品情報を全て入力した状態で「出品する」ボタンを押しても出品が出来ない（一覧に表示されない）状態です。
> 
> **○出品画面にて、画像が選択されていない場合にエラーメッセージが表示されるよう実装しましょう。**
> 現在は、画像を選択していなくてもエラーメッセージが出ない状態です。
> 
> **○一覧から詳細ページに遷移できるよう実装しましょう。**
> 現在は、一覧にて商品をクリックしても詳細に遷移しない状態です。
> 
> ※上記の理由から、商品出品・購入・編集・削除の挙動確認ができていない為、次回ご提出時に併せて確認させていただきます。
> 
> 修正次第、以下の最終課題完了報告フォームを再度提出お願いします！
> ※新しいissueを作っていただく必要はありません
> https://forms.gle/dYuR1wjeHepbEhU7A

再確認お願いします！

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回ご依頼させていただいた項目は修正確認できました✨
ただし、追加で修正していただきたい項目がございましたので、以下のご確認をお願いします！

**[修正依頼項目]**

- [x] URLを直接入力して購入済み商品の購入ページへ遷移しようとすると、トップページに遷移する

**→現在は、購入ページに遷移されてしまう状態です。トップページに遷移されるよう実装しましょう。**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A
※新しいissueを作っていただく必要はありません

**Comment by shunsuke-oka** [comment]
> ご提出ありがとうございます！
> 挙動確認させて頂いたところ、前回ご依頼させていただいた項目は修正確認できました✨
> ただし、追加で修正していただきたい項目がございましたので、以下のご確認をお願いします！
> 
> **[修正依頼項目]**
> 
> * [x]  URLを直接入力して購入済み商品の購入ページへ遷移しようとすると、トップページに遷移する
> 
> **→現在は、購入ページに遷移されてしまう状態です。トップページに遷移されるよう実装しましょう。**
> 
> 修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
> https://forms.gle/dYuR1wjeHepbEhU7A
> ※新しいissueを作っていただく必要はありません

修正しました！

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！お疲れさまでした！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
